server {
    listen 80;  #80 portundan http isteklerini dinle

    location /api/ {  #adres api ile başlıyorsa backend'e yönlendir
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ { #django admin paneli için backend'e yönlendir
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / { #yukarıdaki iki durum dışında kalan tüm istekleri frontend'e yönlendir
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}